server:
  port: 9094
  
#database configuration 
spring:   
  datasource:
    url: jdbc:mysql://localhost:3306/01_MajorProject
    username: root
    password: neerajeg
    driver-class-name: com.mysql.cj.jdbc.Driver
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
   





  